USE [GESTION_HUMANA_HITSS]
GO
/****** Object:  Table [CONFIGURACIONES].[TIPOS_CORREOS]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CONFIGURACIONES].[TIPOS_CORREOS](
	[COD_TIPO_CORREO] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](50) NOT NULL,
	[ESTADO] [numeric](1, 0) NOT NULL,
	[COD_USUARIO_CREA] [nvarchar](128) NOT NULL,
	[FECHA_CREA] [datetime] NOT NULL,
	[COD_USUARIO_MODIFICA] [nvarchar](128) NOT NULL,
	[FECHA_MODIFICA] [datetime] NOT NULL,
 CONSTRAINT [PK_TIPO_CORREO] PRIMARY KEY CLUSTERED 
(
	[COD_TIPO_CORREO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'1 ACTIVO, 2 SUSPENDIDO, 3 ANULADO / ELIMINADO' , @level0type=N'SCHEMA',@level0name=N'CONFIGURACIONES', @level1type=N'TABLE',@level1name=N'TIPOS_CORREOS', @level2type=N'COLUMN',@level2name=N'ESTADO'
GO
/****** Object:  Table [REFERENCIAS].[TIPO_SOPORTES]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [REFERENCIAS].[TIPO_SOPORTES](
	[COD_TIPO_SOPORTE] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](50) NOT NULL,
	[ESTADO] [numeric](1, 0) NOT NULL,
	[COD_USUARIO_CREA] [nvarchar](128) NOT NULL,
	[FECHA_CREA] [datetime] NOT NULL,
	[COD_USUARIO_MODIFICA] [nvarchar](128) NOT NULL,
	[FECHA_MODIFICA] [datetime] NOT NULL,
 CONSTRAINT [PK_TIPO_SOPORTES] PRIMARY KEY CLUSTERED 
(
	[COD_TIPO_SOPORTE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'1 ACTIVO, 2 SUSPENDIDO, 3 ANULADO / ELIMINADO' , @level0type=N'SCHEMA',@level0name=N'REFERENCIAS', @level1type=N'TABLE',@level1name=N'TIPO_SOPORTES', @level2type=N'COLUMN',@level2name=N'ESTADO'
GO
/****** Object:  Table [REQUISICION].[TIPO_NECESIDAD]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [REQUISICION].[TIPO_NECESIDAD](
	[COD_TIPO_NECESIDAD] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_NECESIDAD] [varchar](50) NULL,
	[ESTADO] [bit] NULL,
	[USUARIO_CREACION] [varchar](50) NULL,
	[FECHA_CREACION] [date] NULL,
	[USUARIO_MODIFICACION] [varchar](50) NULL,
	[FECHA_MODIFICACION] [date] NULL,
 CONSTRAINT [PK_TIPONECESIDAD] PRIMARY KEY CLUSTERED 
(
	[COD_TIPO_NECESIDAD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [REQUISICION].[TIPO_DOCUMENTO]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [REQUISICION].[TIPO_DOCUMENTO](
	[COD_TIPO_DOCUMENTO] [int] IDENTITY(1,1) NOT NULL,
	[TIPO_DOCUMENTO] [varchar](50) NULL,
 CONSTRAINT [PK_TIPODOCUMENTO] PRIMARY KEY CLUSTERED 
(
	[COD_TIPO_DOCUMENTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [REQUISICION].[TIPO]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [REQUISICION].[TIPO](
	[COD_TIPO_REQUISICION] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_REQUISICION] [varchar](50) NULL,
	[DESCRIPCION] [varchar](50) NULL,
	[ESTADO] [bit] NULL,
	[USUARIO_CREACION] [varchar](50) NULL,
	[FECHA_CREACION] [date] NULL,
	[USUARIO_MODIFICACION] [varchar](50) NULL,
	[FECHA_MODIFICACION] [date] NULL,
 CONSTRAINT [PK_TIPOREQUISICION] PRIMARY KEY CLUSTERED 
(
	[COD_TIPO_REQUISICION] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [REQUISICION].[ROL_REQUISICION]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [REQUISICION].[ROL_REQUISICION](
	[COD_ID_ROL_REQUISICION] [int] IDENTITY(1,1) NOT NULL,
	[ID_ROL] [nvarchar](128) NULL,
	[COD_TIPO_REQUISICION] [int] NULL,
	[COD_ESTADO_REQUISICION] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[COD_ID_ROL_REQUISICION] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [REQUISICION].[ROL]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [REQUISICION].[ROL](
	[COD_ROL] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NULL,
	[USUARIO_CREACION] [varchar](50) NULL,
	[FECHA_CREACION] [date] NULL,
	[USUARIO_MODIFICACION] [varchar](50) NULL,
	[FECHA_MODIFICACION] [date] NULL,
 CONSTRAINT [PK_ROL] PRIMARY KEY CLUSTERED 
(
	[COD_ROL] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[AspNetRoles]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetRoles](
	[Id] [nvarchar](128) NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK_dbo.AspNetRoles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Log]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Log](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Date] [datetime] NOT NULL,
	[Thread] [varchar](255) NOT NULL,
	[Level] [varchar](50) NOT NULL,
	[Logger] [varchar](255) NOT NULL,
	[Message] [varchar](4000) NOT NULL,
	[Exception] [varchar](2000) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [REQUISICION].[OPCIONES_MENU]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [REQUISICION].[OPCIONES_MENU](
	[COD_OPCIONES_MENU] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_OPCION] [varchar](50) NULL,
	[DESCRIPCION] [varchar](50) NULL,
	[ESTADO] [bit] NULL,
	[USUARIO_CREACION] [varchar](50) NULL,
	[FECHA_CREACION] [date] NULL,
	[USUARIO_MODIFICACION] [varchar](50) NULL,
	[FECHA_MODIFICACION] [date] NULL,
 CONSTRAINT [PK_OPCIONESMENU] PRIMARY KEY CLUSTERED 
(
	[COD_OPCIONES_MENU] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [AUDITORIAS].[MODIFICACIONES]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [AUDITORIAS].[MODIFICACIONES](
	[COD_AUDITORIA] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[COD_TABLA] [numeric](18, 0) NOT NULL,
	[TABLA] [nvarchar](50) NOT NULL,
	[COLUMNA] [nvarchar](50) NOT NULL,
	[DATO_ANTERIOR] [nvarchar](max) NOT NULL,
	[DATO_NUEVO] [nvarchar](max) NOT NULL,
	[COD_USUARIO_MODIFICO] [nvarchar](126) NOT NULL,
	[FECHA_MODIFICACION] [datetime] NOT NULL,
 CONSTRAINT [PK_MODIFICACIONES] PRIMARY KEY CLUSTERED 
(
	[COD_AUDITORIA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [RETIROS].[ESTADOS]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RETIROS].[ESTADOS](
	[COD_ESTADO_RETIRO] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](100) NOT NULL,
	[ESTADO] [numeric](1, 0) NOT NULL,
	[COD_USUARIO_CREA] [nvarchar](128) NOT NULL,
	[FECHA_CREA] [datetime] NOT NULL,
	[COD_USUARIO_MODIFICA] [nvarchar](128) NOT NULL,
	[FECHA_MODIFICA] [datetime] NOT NULL,
 CONSTRAINT [PK_ESTADOS] PRIMARY KEY CLUSTERED 
(
	[COD_ESTADO_RETIRO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'1 ACTIVO, 2 SUSPENDIDO, 3 ANULADO / ELIMINADO' , @level0type=N'SCHEMA',@level0name=N'RETIROS', @level1type=N'TABLE',@level1name=N'ESTADOS', @level2type=N'COLUMN',@level2name=N'ESTADO'
GO
/****** Object:  Table [REQUISICION].[ESTADO]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [REQUISICION].[ESTADO](
	[COD_ESTADO_REQUISICION] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_ESTADO] [varchar](50) NULL,
	[USUARIO_CREACION] [varchar](50) NULL,
	[FECHA_CREACION] [date] NULL,
	[USARIO_MODIFICACION] [varchar](50) NULL,
	[FECHA_MODIFICACION] [date] NULL,
	[COLOR] [varchar](50) NULL,
 CONSTRAINT [PK_ESTADOSREQUISICION] PRIMARY KEY CLUSTERED 
(
	[COD_ESTADO_REQUISICION] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [AUDITORIAS].[ERRORES]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [AUDITORIAS].[ERRORES](
	[COD_ERROR] [int] IDENTITY(1,1) NOT NULL,
	[FECHA] [datetime] NOT NULL,
	[NOMBRE_CLASE] [varchar](50) NULL,
	[NOMBRE_METODO] [varchar](50) NULL,
	[CODIGO_ERROR] [varchar](20) NULL,
	[DETALLE] [varchar](max) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [REQUISICION].[DIAS_LABORALES]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [REQUISICION].[DIAS_LABORALES](
	[COD_DIAS_LABORALES] [int] IDENTITY(1,1) NOT NULL,
	[DIA_SEMANA] [varchar](50) NULL,
	[USUARIO_CREACION] [varchar](50) NULL,
	[FECHA_CREACION] [date] NULL,
	[USUARIO_MODIFICACION] [varchar](50) NULL,
	[FECHA_MODIFICACION] [date] NULL,
 CONSTRAINT [PK_DIASLABORALES] PRIMARY KEY CLUSTERED 
(
	[COD_DIAS_LABORALES] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [AUDITORIAS].[DEPURARCION]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [AUDITORIAS].[DEPURARCION](
	[COD_ERROR] [int] IDENTITY(1,1) NOT NULL,
	[FECHA] [datetime] NOT NULL,
	[NOMBRE_CLASE] [varchar](50) NULL,
	[NOMBRE_METODO] [varchar](50) NULL,
	[CODIGO_ERROR] [varchar](20) NULL,
	[DETALLE] [varchar](max) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[AspNetUsers]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUsers](
	[Id] [nvarchar](128) NOT NULL,
	[Email] [nvarchar](256) NULL,
	[EmailConfirmed] [bit] NOT NULL,
	[PasswordHash] [nvarchar](max) NULL,
	[SecurityStamp] [nvarchar](max) NULL,
	[PhoneNumber] [nvarchar](max) NULL,
	[PhoneNumberConfirmed] [bit] NOT NULL,
	[TwoFactorEnabled] [bit] NOT NULL,
	[LockoutEndDateUtc] [datetime] NULL,
	[LockoutEnabled] [bit] NOT NULL,
	[AccessFailedCount] [int] NOT NULL,
	[UserName] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK_dbo.AspNetUsers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUserRoles]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserRoles](
	[UserId] [nvarchar](128) NOT NULL,
	[RoleId] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_dbo.AspNetUserRoles] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[RoleId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUserLogins]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserLogins](
	[LoginProvider] [nvarchar](128) NOT NULL,
	[ProviderKey] [nvarchar](128) NOT NULL,
	[UserId] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_dbo.AspNetUserLogins] PRIMARY KEY CLUSTERED 
(
	[LoginProvider] ASC,
	[ProviderKey] ASC,
	[UserId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUserClaims]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserClaims](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [nvarchar](128) NOT NULL,
	[ClaimType] [nvarchar](max) NULL,
	[ClaimValue] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.AspNetUserClaims] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CONFIGURACIONES].[CORREOS]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CONFIGURACIONES].[CORREOS](
	[COD_CORREO] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[COD_TIPO_CORREO] [numeric](18, 0) NOT NULL,
	[SERVIDOR_SMTP] [nvarchar](100) NOT NULL,
	[CUENTA_CORREO] [nvarchar](100) NOT NULL,
	[CUENTA] [nvarchar](100) NOT NULL,
	[SALTO] [nvarchar](100) NOT NULL,
	[IV] [nvarchar](100) NOT NULL,
	[CONTRASENA] [nvarchar](100) NOT NULL,
	[ES_HTML] [bit] NOT NULL,
	[USA_SSL] [bit] NOT NULL,
	[ESTADO] [numeric](1, 0) NOT NULL,
	[COD_USUARIO_CREA] [nvarchar](128) NOT NULL,
	[FECHA_CREA] [datetime] NOT NULL,
	[COD_USUARIO_MODIFICA] [nvarchar](128) NOT NULL,
	[FECHA_MODIFICA] [datetime] NOT NULL,
	[PUERTO] [numeric](18, 0) NOT NULL,
	[ASUNTO] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_COREEOS] PRIMARY KEY CLUSTERED 
(
	[COD_CORREO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'1 ACTIVO, 2 SUSPENDIDO, 3 ANULADO / ELIMINADO' , @level0type=N'SCHEMA',@level0name=N'CONFIGURACIONES', @level1type=N'TABLE',@level1name=N'CORREOS', @level2type=N'COLUMN',@level2name=N'ESTADO'
GO
/****** Object:  Table [REQUISICION].[MENU_ROL]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [REQUISICION].[MENU_ROL](
	[COD_MENU_ROL] [int] IDENTITY(1,1) NOT NULL,
	[COD_ROL] [int] NOT NULL,
	[COD_OPCIONES_MENU] [int] NOT NULL,
	[USUARIO_CREACION] [varchar](50) NULL,
	[FECHA_CREACION] [date] NULL,
	[USUARIO_MODIFICACION] [varchar](50) NULL,
	[FECHA_MODIFICACION] [date] NULL,
 CONSTRAINT [PK_MENUROL] PRIMARY KEY CLUSTERED 
(
	[COD_MENU_ROL] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [RETIROS].[RETIROS]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RETIROS].[RETIROS](
	[COD_RETIRO] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[NUMERO_DOCUMENTO] [nvarchar](50) NOT NULL,
	[NOMBRE] [nvarchar](200) NOT NULL,
	[USUARIO] [nvarchar](50) NOT NULL,
	[COD_CARGO] [numeric](18, 0) NOT NULL,
	[NOMBRE_CARGO] [nvarchar](80) NOT NULL,
	[COD_CAUSA_RETIRO] [numeric](18, 0) NOT NULL,
	[NOMBRE_CAUSA_RETIRO] [nvarchar](100) NOT NULL,
	[FECHA_RETIRO] [date] NOT NULL,
	[GENERA_VACANTE] [bit] NOT NULL,
	[COMENTARIOS] [nvarchar](max) NOT NULL,
	[APROBADO] [bit] NOT NULL,
	[COD_ESTADO_RETIRO] [numeric](18, 0) NOT NULL,
	[ESTADO] [numeric](1, 0) NOT NULL,
	[COD_USUARIO_CREA] [nvarchar](128) NOT NULL,
	[FECHA_CREA] [datetime] NOT NULL,
	[COD_USUARIO_MODIFICA] [nvarchar](128) NOT NULL,
	[FECHA_MODIFICA] [datetime] NOT NULL,
 CONSTRAINT [PK_RETIROS] PRIMARY KEY CLUSTERED 
(
	[COD_RETIRO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'1 SI, 0 NO' , @level0type=N'SCHEMA',@level0name=N'RETIROS', @level1type=N'TABLE',@level1name=N'RETIROS', @level2type=N'COLUMN',@level2name=N'GENERA_VACANTE'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'1 APROBADO , 0 NO APROBADO' , @level0type=N'SCHEMA',@level0name=N'RETIROS', @level1type=N'TABLE',@level1name=N'RETIROS', @level2type=N'COLUMN',@level2name=N'APROBADO'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'1 ACTIVO, 2 SUSPENDIDO, 3 ANULADO / ELIMINADO' , @level0type=N'SCHEMA',@level0name=N'RETIROS', @level1type=N'TABLE',@level1name=N'RETIROS', @level2type=N'COLUMN',@level2name=N'ESTADO'
GO
/****** Object:  Table [REQUISICION].[REQUISICION]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [REQUISICION].[REQUISICION](
	[COD_REQUISICION] [int] IDENTITY(1,1) NOT NULL,
	[COD_TIPO_NECESIDAD] [int] NULL,
	[COD_CARGO] [int] NULL,
	[NOMBRE_CARGO] [varchar](100) NULL,
	[ORDEN] [varchar](100) NULL,
	[COD_CECO] [varchar](100) NULL,
	[NOMBRE_CECO] [varchar](100) NULL,
	[COD_TIPO_REQUISICION] [int] NULL,
	[FECHA_INICIO] [date] NULL,
	[FECHA_FIN] [date] NULL,
	[ES_MODIFICACION] [bit] NULL,
	[OBSERVACION] [varchar](200) NULL,
	[COD_ESTADO_REQUISICION] [int] NULL,
	[USUARIO_CREACION] [varchar](50) NULL,
	[FECHA_CREACION] [date] NULL,
	[USUARIO_MODIFICACION] [varchar](50) NULL,
	[FECHA_MODIFICACION] [date] NULL,
	[COD_GERENCIA] [int] NULL,
	[NOMBRE_GERENCIA] [varchar](100) NULL,
	[COD_TIPO_CONTRATO] [int] NULL,
	[NOMBRE_TIPO_CONTRATO] [varchar](100) NULL,
	[COD_TIPO_DOCUMENTO] [int] NULL,
	[NUMERO_DOCUMENTO_EMPLEADO] [varchar](50) NULL,
	[NOMBRE_EMPLEADO] [varchar](100) NULL,
	[JEFE_INMEDIATO] [varchar](100) NULL,
	[COD_SOCIEDAD] [int] NULL,
	[NOMBRE_SOCIEDAD] [varchar](100) NULL,
	[COD_EQUIPO_VENTAS] [int] NULL,
	[NOMBRE_EQUIPO_VENTAS] [varchar](100) NULL,
	[COD_CIUDAD_TRABAJO] [int] NULL,
	[NOMBRE_CIUDAD_TRABAJO] [varchar](100) NULL,
	[COD_DANE_CIUDAD_TRABAJO] [int] NULL,
	[COD_UBICACION_FISICA] [int] NULL,
	[NOMBRE_UBICACION_FISICA] [varchar](100) NULL,
	[COD_NIVEL_RIESGO_ARL] [int] NULL,
	[NIVEL_RIESGO_ARL] [varchar](100) NULL,
	[COD_CATEGORIA_ED] [int] NULL,
	[NOMBRE_CATEGORIA_ED] [varchar](100) NULL,
	[CARGO_CRITICO] [bit] NULL,
	[COD_JORNADA_LABORAL] [int] NULL,
	[NOMBRE_JORNADA_LABORAL] [varchar](100) NULL,
	[HORARIO_LABORAL_DESDE] [varchar](50) NULL,
	[HORARIO_LABORAL_HASTA] [varchar](50) NULL,
	[COD_DIA_LABORAL_DESDE] [int] NULL,
	[COD_DIA_LABORAL_HASTA] [int] NULL,
	[POSICION] [varchar](100) NULL,
	[EMPRESA_TEMPORAL] [varchar](100) NULL,
	[SALARIO_FIJO] [numeric](18, 2) NULL,
	[PORCENTAJE_SALARIO_FIJO] [numeric](18, 2) NULL,
	[SALARIO_VARIABLE] [numeric](18, 2) NULL,
	[PORCENTAJE_SALARIO_VARIABLE] [numeric](18, 2) NULL,
	[SOBREREMUNERACION] [numeric](18, 2) NULL,
	[PORCENTAJE_SOBREREMUNERACION] [numeric](18, 2) NULL,
	[EXTRA_FIJA] [numeric](18, 2) NULL,
	[RECARGO_NOCTURNO] [numeric](18, 2) NULL,
	[MEDIO_TRANSPORTE] [numeric](18, 2) NULL,
	[SALARIO_TOTAL] [numeric](18, 2) NULL,
	[BONO_ANUAL] [numeric](18, 2) NULL,
	[NUMERO_SALARIOS] [int] NULL,
	[MESES_GARANTIZADOS] [int] NULL,
	[COD_TIPO_SALARIO] [int] NULL,
	[NOMBRE_TIPO_SALARIO] [varchar](50) NULL,
	[FACTOR_PRESTACIONAL] [numeric](18, 2) NULL,
	[INGRESO_PROM_MENSUAL] [numeric](18, 2) NULL,
	[INGRESO_PROM_ANUAL] [numeric](18, 2) NULL,
	[MERCADO] [varchar](100) NULL,
	[COD_CATEGORIA] [int] NULL,
	[NOMBRE_CATEGORIA] [varchar](100) NULL,
	[PUNTO_MEDIO_80] [numeric](18, 2) NULL,
	[PUNTO_MEDIO_100] [numeric](18, 2) NULL,
	[PUNTO_MEDIO_120] [numeric](18, 2) NULL,
	[POSICIONAMIENTO] [numeric](18, 2) NULL,
	[EMAIL_USUARIO_CREACION] [varchar](100) NULL,
	[LOGIN_EMPLEADO] [varchar](50) NULL,
 CONSTRAINT [PK_REQUISICION] PRIMARY KEY CLUSTERED 
(
	[COD_REQUISICION] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [REFERENCIAS].[CAUSA_RETIROS_TIPO_SOPORTES]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [REFERENCIAS].[CAUSA_RETIROS_TIPO_SOPORTES](
	[COD_CAUSA_RETIRO_TIPO_SOPORTE] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[COD_CAUSA_RETIRO] [numeric](18, 0) NOT NULL,
	[COD_TIPO_SOPORTE] [numeric](18, 0) NOT NULL,
	[REQUERIDO] [bit] NOT NULL,
	[ESTADO] [numeric](1, 0) NOT NULL,
	[COD_USUARIO_CREA] [nvarchar](128) NOT NULL,
	[FECHA_CREA] [datetime] NOT NULL,
	[COD_USUARIO_MODIFICA] [nvarchar](128) NOT NULL,
	[FECHA_MODIFICA] [datetime] NOT NULL,
 CONSTRAINT [PK_CAUSA_RETIRO_TIPO_SOPORTES] PRIMARY KEY CLUSTERED 
(
	[COD_CAUSA_RETIRO_TIPO_SOPORTE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'1 ACTIVO, 2 SUSPENDIDO, 3 ANULADO / ELIMINADO' , @level0type=N'SCHEMA',@level0name=N'REFERENCIAS', @level1type=N'TABLE',@level1name=N'CAUSA_RETIROS_TIPO_SOPORTES', @level2type=N'COLUMN',@level2name=N'ESTADO'
GO
/****** Object:  Table [RETIROS].[SOPORTES]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RETIROS].[SOPORTES](
	[COD_SOPORTE] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[COD_RETIRO] [numeric](18, 0) NOT NULL,
	[COD_TIPO_SOPORTE] [numeric](18, 0) NOT NULL,
	[RUTA_SOPORTE] [nvarchar](max) NULL,
	[NOMBRE_SOPORTE] [nvarchar](200) NULL,
	[TAMANO] [nvarchar](10) NULL,
	[APROBADO] [bit] NOT NULL,
	[ESTADO] [numeric](1, 0) NOT NULL,
	[COD_USUARIO_CREA] [nvarchar](128) NOT NULL,
	[FECHA_CREA] [datetime] NOT NULL,
	[COD_USUARIO_MODIFICA] [nvarchar](128) NOT NULL,
	[FECHA_MODIFICA] [datetime] NOT NULL,
 CONSTRAINT [PK_SOPORTS] PRIMARY KEY CLUSTERED 
(
	[COD_SOPORTE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'1 ACTIVO, 2 SUSPENDIDO, 3 ANULADO / ELIMINADO' , @level0type=N'SCHEMA',@level0name=N'RETIROS', @level1type=N'TABLE',@level1name=N'SOPORTES', @level2type=N'COLUMN',@level2name=N'ESTADO'
GO
/****** Object:  Table [CONFIGURACIONES].[PLANTILLAS_CORREOS]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CONFIGURACIONES].[PLANTILLAS_CORREOS](
	[COD_PLANTILLA] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[COD_CORREO] [numeric](18, 0) NOT NULL,
	[PLANTILLA] [nvarchar](max) NOT NULL,
	[ESTADO] [numeric](1, 0) NOT NULL,
	[COD_USUARIO_CREA] [nvarchar](128) NOT NULL,
	[FECHA_CREA] [datetime] NOT NULL,
	[COD_USUARIO_MODIFICA] [nvarchar](128) NOT NULL,
	[FECHA_MODIFICA] [datetime] NOT NULL,
 CONSTRAINT [PK_PLANTILLAS_CORREOS] PRIMARY KEY CLUSTERED 
(
	[COD_PLANTILLA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'1 ACTIVO, 2 SUSPENDIDO, 3 ANULADO / ELIMINADO' , @level0type=N'SCHEMA',@level0name=N'CONFIGURACIONES', @level1type=N'TABLE',@level1name=N'PLANTILLAS_CORREOS', @level2type=N'COLUMN',@level2name=N'ESTADO'
GO
/****** Object:  Table [REQUISICION].[HISTORICO]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [REQUISICION].[HISTORICO](
	[COD_HISTORICO_REQUISICION] [int] IDENTITY(1,1) NOT NULL,
	[COD_REQUISICION] [int] NOT NULL,
	[COD_ROL] [int] NOT NULL,
	[COD_NIVEL_RIESGO_ARL] [int] NULL,
	[COD_CATEGORIA_ED] [int] NULL,
	[CARGO_CRITICO] [bit] NULL,
	[COD_JORNADA_LABORAL] [int] NULL,
	[HORARIO_LABORAL_DESDE] [varchar](50) NULL,
	[HORARIO_LABORAL_HASTA] [varchar](50) NULL,
	[COD_DIA_LABORAL_DESDE] [int] NULL,
	[COD_DIA_LABORAL_HASTA] [int] NULL,
	[SALARIO_FIJO] [numeric](18, 2) NULL,
	[PORCENTAJE_SALARIO_FIJO] [numeric](18, 2) NULL,
	[SALARIO_VARIABLE] [numeric](18, 2) NULL,
	[PORCENTAJE_SALARIO_VARIABLE] [numeric](18, 2) NULL,
	[SOBREREMUNERACION] [numeric](18, 2) NULL,
	[PORCENTAJE_SOBREREMUNERACION] [numeric](18, 2) NULL,
	[EXTRA_FIJA] [numeric](18, 2) NULL,
	[RECARGO_NOCTURNO] [numeric](18, 2) NULL,
	[MEDIO_TRANSPORTE] [varchar](50) NULL,
	[SALARIO_TOTAL] [numeric](18, 2) NULL,
	[BONO_ANUAL] [numeric](18, 2) NULL,
	[NUMERO_SALARIOS] [int] NULL,
	[MESES_GARANTIZADOS] [int] NULL,
	[COD_TIPO_SALARIO] [int] NULL,
	[FACTOR_PRESTACIONAL] [varchar](50) NULL,
	[INGRESO_PROM_MENSUAL] [numeric](18, 2) NULL,
	[INGRESO_PROM_ANUAL] [numeric](18, 2) NULL,
	[MERCADO] [varchar](50) NULL,
	[COD_CATEGORIA] [int] NULL,
	[PUNTO_MEDIO_80] [numeric](18, 2) NULL,
	[PUNTO_MEDIO_100] [numeric](18, 2) NULL,
	[PUNTO_MEDIO_120] [numeric](18, 2) NULL,
	[POSICIONAMIENTO] [varchar](50) NULL,
	[USUARIO_REGISTRO] [varchar](50) NOT NULL,
	[FECHA_REGISTRO] [date] NOT NULL,
	[COD_ESTADO] [int] NOT NULL,
 CONSTRAINT [PK_REQUISICION.HISTORICO_REQUISICION] PRIMARY KEY CLUSTERED 
(
	[COD_HISTORICO_REQUISICION] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [CONFIGURACIONES].[CORREOS_DESTINOS]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CONFIGURACIONES].[CORREOS_DESTINOS](
	[COD_CORREO_DESTINO] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[COD_CORREO] [numeric](18, 0) NOT NULL,
	[CORREO] [nvarchar](50) NOT NULL,
	[ESTADO] [numeric](1, 0) NOT NULL,
	[COD_USUARIO_CREA] [nvarchar](128) NOT NULL,
	[FECHA_CREA] [datetime] NOT NULL,
	[COD_USUARIO_MODIFICA] [nvarchar](128) NOT NULL,
	[FECHA_MODIFICA] [datetime] NOT NULL,
 CONSTRAINT [PK_CORREOS_DESTINOS] PRIMARY KEY CLUSTERED 
(
	[COD_CORREO_DESTINO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'1 ACTIVO, 2 SUSPENDIDO, 3 ANULADO / ELIMINADO' , @level0type=N'SCHEMA',@level0name=N'CONFIGURACIONES', @level1type=N'TABLE',@level1name=N'CORREOS_DESTINOS', @level2type=N'COLUMN',@level2name=N'ESTADO'
GO
/****** Object:  Table [REQUISICION].[COMENTARIO]    Script Date: 05/20/2019 10:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [REQUISICION].[COMENTARIO](
	[COD_COMENTARIO] [int] IDENTITY(1,1) NOT NULL,
	[COD_REQUISICION] [int] NULL,
	[COD_ESTADO_REQUISICION] [int] NULL,
	[COMENTARIO_AUTORIZACION] [varchar](200) NULL,
	[OBSERVACIONES] [varchar](200) NULL,
	[COD_ROL] [int] NULL,
	[COD_USUARIO] [int] NULL,
	[USARIO_CREACION] [varchar](100) NULL,
	[FECHA_CREACION] [date] NULL,
 CONSTRAINT [PK_REQUISICION.COMENTARIO] PRIMARY KEY CLUSTERED 
(
	[COD_COMENTARIO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Default [DF_DEPURARCION_FECHA]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [AUDITORIAS].[DEPURARCION] ADD  CONSTRAINT [DF_DEPURARCION_FECHA]  DEFAULT (getdate()) FOR [FECHA]
GO
/****** Object:  Default [DF_ERRORES_FECHA]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [AUDITORIAS].[ERRORES] ADD  CONSTRAINT [DF_ERRORES_FECHA]  DEFAULT (getdate()) FOR [FECHA]
GO
/****** Object:  Default [DF_COREEOS_ESTADO]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [CONFIGURACIONES].[CORREOS] ADD  CONSTRAINT [DF_COREEOS_ESTADO]  DEFAULT ((1)) FOR [ESTADO]
GO
/****** Object:  Default [DF_COREEOS_FECHA_CREA]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [CONFIGURACIONES].[CORREOS] ADD  CONSTRAINT [DF_COREEOS_FECHA_CREA]  DEFAULT (getdate()) FOR [FECHA_CREA]
GO
/****** Object:  Default [DF_COREEOS_FECHA_MODIFICA]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [CONFIGURACIONES].[CORREOS] ADD  CONSTRAINT [DF_COREEOS_FECHA_MODIFICA]  DEFAULT (getdate()) FOR [FECHA_MODIFICA]
GO
/****** Object:  Default [DF_CORREOS_DESTINOS_ESTADO]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [CONFIGURACIONES].[CORREOS_DESTINOS] ADD  CONSTRAINT [DF_CORREOS_DESTINOS_ESTADO]  DEFAULT ((1)) FOR [ESTADO]
GO
/****** Object:  Default [DF_CORREOS_DESTINOS_FECHA_CREA]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [CONFIGURACIONES].[CORREOS_DESTINOS] ADD  CONSTRAINT [DF_CORREOS_DESTINOS_FECHA_CREA]  DEFAULT (getdate()) FOR [FECHA_CREA]
GO
/****** Object:  Default [DF_CORREOS_DESTINOS_FECHA_MODIFICA]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [CONFIGURACIONES].[CORREOS_DESTINOS] ADD  CONSTRAINT [DF_CORREOS_DESTINOS_FECHA_MODIFICA]  DEFAULT (getdate()) FOR [FECHA_MODIFICA]
GO
/****** Object:  Default [DF_PLANTILLAS_CORREOS_ESTADO]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [CONFIGURACIONES].[PLANTILLAS_CORREOS] ADD  CONSTRAINT [DF_PLANTILLAS_CORREOS_ESTADO]  DEFAULT ((1)) FOR [ESTADO]
GO
/****** Object:  Default [DF_PLANTILLAS_CORREOS_FECHA_CREA]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [CONFIGURACIONES].[PLANTILLAS_CORREOS] ADD  CONSTRAINT [DF_PLANTILLAS_CORREOS_FECHA_CREA]  DEFAULT (getdate()) FOR [FECHA_CREA]
GO
/****** Object:  Default [DF_PLANTILLAS_CORREOS_FECHA_MODIFICA]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [CONFIGURACIONES].[PLANTILLAS_CORREOS] ADD  CONSTRAINT [DF_PLANTILLAS_CORREOS_FECHA_MODIFICA]  DEFAULT (getdate()) FOR [FECHA_MODIFICA]
GO
/****** Object:  Default [DF_TIPO_CORREO_ESTADO]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [CONFIGURACIONES].[TIPOS_CORREOS] ADD  CONSTRAINT [DF_TIPO_CORREO_ESTADO]  DEFAULT ((1)) FOR [ESTADO]
GO
/****** Object:  Default [DF_TIPO_CORREO_FECHA_CREA]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [CONFIGURACIONES].[TIPOS_CORREOS] ADD  CONSTRAINT [DF_TIPO_CORREO_FECHA_CREA]  DEFAULT (getdate()) FOR [FECHA_CREA]
GO
/****** Object:  Default [DF_TIPO_CORREO_FECHA_MODIFICA]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [CONFIGURACIONES].[TIPOS_CORREOS] ADD  CONSTRAINT [DF_TIPO_CORREO_FECHA_MODIFICA]  DEFAULT (getdate()) FOR [FECHA_MODIFICA]
GO
/****** Object:  Default [DF_CAUSA_RETIROS_TIPO_SOPORTES_ESTADO]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [REFERENCIAS].[CAUSA_RETIROS_TIPO_SOPORTES] ADD  CONSTRAINT [DF_CAUSA_RETIROS_TIPO_SOPORTES_ESTADO]  DEFAULT ((1)) FOR [ESTADO]
GO
/****** Object:  Default [DF_CAUSA_RETIROS_TIPO_SOPORTES_FECHA_CREA]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [REFERENCIAS].[CAUSA_RETIROS_TIPO_SOPORTES] ADD  CONSTRAINT [DF_CAUSA_RETIROS_TIPO_SOPORTES_FECHA_CREA]  DEFAULT (getdate()) FOR [FECHA_CREA]
GO
/****** Object:  Default [DF_CAUSA_RETIROS_TIPO_SOPORTES_FECHA_MODIFICA]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [REFERENCIAS].[CAUSA_RETIROS_TIPO_SOPORTES] ADD  CONSTRAINT [DF_CAUSA_RETIROS_TIPO_SOPORTES_FECHA_MODIFICA]  DEFAULT (getdate()) FOR [FECHA_MODIFICA]
GO
/****** Object:  Default [DF_TIPO_SOPORTES_ESTADO]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [REFERENCIAS].[TIPO_SOPORTES] ADD  CONSTRAINT [DF_TIPO_SOPORTES_ESTADO]  DEFAULT ((1)) FOR [ESTADO]
GO
/****** Object:  Default [DF_TIPO_SOPORTES_FECHA_CREA]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [REFERENCIAS].[TIPO_SOPORTES] ADD  CONSTRAINT [DF_TIPO_SOPORTES_FECHA_CREA]  DEFAULT (getdate()) FOR [FECHA_CREA]
GO
/****** Object:  Default [DF_TIPO_SOPORTES_FECHA_MODIFICA]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [REFERENCIAS].[TIPO_SOPORTES] ADD  CONSTRAINT [DF_TIPO_SOPORTES_FECHA_MODIFICA]  DEFAULT (getdate()) FOR [FECHA_MODIFICA]
GO
/****** Object:  Default [DF_ESTADOS_ESTADO]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [RETIROS].[ESTADOS] ADD  CONSTRAINT [DF_ESTADOS_ESTADO]  DEFAULT ((1)) FOR [ESTADO]
GO
/****** Object:  Default [DF_ESTADOS_FECHA_CREA]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [RETIROS].[ESTADOS] ADD  CONSTRAINT [DF_ESTADOS_FECHA_CREA]  DEFAULT (getdate()) FOR [FECHA_CREA]
GO
/****** Object:  Default [DF_ESTADOS_FECHA_MODIFICA]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [RETIROS].[ESTADOS] ADD  CONSTRAINT [DF_ESTADOS_FECHA_MODIFICA]  DEFAULT (getdate()) FOR [FECHA_MODIFICA]
GO
/****** Object:  Default [DF_RETIROS_FECHA_CREA]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [RETIROS].[RETIROS] ADD  CONSTRAINT [DF_RETIROS_FECHA_CREA]  DEFAULT (getdate()) FOR [FECHA_CREA]
GO
/****** Object:  Default [DF_RETIROS_FECHA_MODIFICA]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [RETIROS].[RETIROS] ADD  CONSTRAINT [DF_RETIROS_FECHA_MODIFICA]  DEFAULT (getdate()) FOR [FECHA_MODIFICA]
GO
/****** Object:  ForeignKey [FK_COREEOS_TIPOS_CORREOS]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [CONFIGURACIONES].[CORREOS]  WITH CHECK ADD  CONSTRAINT [FK_COREEOS_TIPOS_CORREOS] FOREIGN KEY([COD_TIPO_CORREO])
REFERENCES [CONFIGURACIONES].[TIPOS_CORREOS] ([COD_TIPO_CORREO])
GO
ALTER TABLE [CONFIGURACIONES].[CORREOS] CHECK CONSTRAINT [FK_COREEOS_TIPOS_CORREOS]
GO
/****** Object:  ForeignKey [FK_CORREOS_DESTINOS_COREEOS]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [CONFIGURACIONES].[CORREOS_DESTINOS]  WITH CHECK ADD  CONSTRAINT [FK_CORREOS_DESTINOS_COREEOS] FOREIGN KEY([COD_CORREO])
REFERENCES [CONFIGURACIONES].[CORREOS] ([COD_CORREO])
GO
ALTER TABLE [CONFIGURACIONES].[CORREOS_DESTINOS] CHECK CONSTRAINT [FK_CORREOS_DESTINOS_COREEOS]
GO
/****** Object:  ForeignKey [FK_PLANTILLAS_CORREOS_COREEOS]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [CONFIGURACIONES].[PLANTILLAS_CORREOS]  WITH CHECK ADD  CONSTRAINT [FK_PLANTILLAS_CORREOS_COREEOS] FOREIGN KEY([COD_CORREO])
REFERENCES [CONFIGURACIONES].[CORREOS] ([COD_CORREO])
GO
ALTER TABLE [CONFIGURACIONES].[PLANTILLAS_CORREOS] CHECK CONSTRAINT [FK_PLANTILLAS_CORREOS_COREEOS]
GO
/****** Object:  ForeignKey [FK_dbo.AspNetUserClaims_dbo.AspNetUsers_UserId]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [dbo].[AspNetUserClaims]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AspNetUserClaims_dbo.AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserClaims] CHECK CONSTRAINT [FK_dbo.AspNetUserClaims_dbo.AspNetUsers_UserId]
GO
/****** Object:  ForeignKey [FK_dbo.AspNetUserLogins_dbo.AspNetUsers_UserId]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [dbo].[AspNetUserLogins]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AspNetUserLogins_dbo.AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserLogins] CHECK CONSTRAINT [FK_dbo.AspNetUserLogins_dbo.AspNetUsers_UserId]
GO
/****** Object:  ForeignKey [FK_dbo.AspNetUserRoles_dbo.AspNetRoles_RoleId]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [dbo].[AspNetUserRoles]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetRoles_RoleId] FOREIGN KEY([RoleId])
REFERENCES [dbo].[AspNetRoles] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserRoles] CHECK CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetRoles_RoleId]
GO
/****** Object:  ForeignKey [FK_dbo.AspNetUserRoles_dbo.AspNetUsers_UserId]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [dbo].[AspNetUserRoles]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserRoles] CHECK CONSTRAINT [FK_dbo.AspNetUserRoles_dbo.AspNetUsers_UserId]
GO
/****** Object:  ForeignKey [FK_CAUSA_RETIROS_TIPO_SOPORTES_TIPO_SOPORTES]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [REFERENCIAS].[CAUSA_RETIROS_TIPO_SOPORTES]  WITH CHECK ADD  CONSTRAINT [FK_CAUSA_RETIROS_TIPO_SOPORTES_TIPO_SOPORTES] FOREIGN KEY([COD_TIPO_SOPORTE])
REFERENCES [REFERENCIAS].[TIPO_SOPORTES] ([COD_TIPO_SOPORTE])
GO
ALTER TABLE [REFERENCIAS].[CAUSA_RETIROS_TIPO_SOPORTES] CHECK CONSTRAINT [FK_CAUSA_RETIROS_TIPO_SOPORTES_TIPO_SOPORTES]
GO
/****** Object:  ForeignKey [FK_REQUISICION.COMENTARIO_REQUISICION.REQUISICION]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [REQUISICION].[COMENTARIO]  WITH CHECK ADD  CONSTRAINT [FK_REQUISICION.COMENTARIO_REQUISICION.REQUISICION] FOREIGN KEY([COD_REQUISICION])
REFERENCES [REQUISICION].[REQUISICION] ([COD_REQUISICION])
GO
ALTER TABLE [REQUISICION].[COMENTARIO] CHECK CONSTRAINT [FK_REQUISICION.COMENTARIO_REQUISICION.REQUISICION]
GO
/****** Object:  ForeignKey [FK_REQUISICION.COMENTARIO_REQUISICION.ROL]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [REQUISICION].[COMENTARIO]  WITH CHECK ADD  CONSTRAINT [FK_REQUISICION.COMENTARIO_REQUISICION.ROL] FOREIGN KEY([COD_ROL])
REFERENCES [REQUISICION].[ROL] ([COD_ROL])
GO
ALTER TABLE [REQUISICION].[COMENTARIO] CHECK CONSTRAINT [FK_REQUISICION.COMENTARIO_REQUISICION.ROL]
GO
/****** Object:  ForeignKey [FK_REQUISICION.HISTORICO_REQUISICION.ESTADO]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [REQUISICION].[HISTORICO]  WITH CHECK ADD  CONSTRAINT [FK_REQUISICION.HISTORICO_REQUISICION.ESTADO] FOREIGN KEY([COD_ESTADO])
REFERENCES [REQUISICION].[ESTADO] ([COD_ESTADO_REQUISICION])
GO
ALTER TABLE [REQUISICION].[HISTORICO] CHECK CONSTRAINT [FK_REQUISICION.HISTORICO_REQUISICION.ESTADO]
GO
/****** Object:  ForeignKey [FK_REQUISICION.HISTORICO_REQUISICION.REQUISICION]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [REQUISICION].[HISTORICO]  WITH CHECK ADD  CONSTRAINT [FK_REQUISICION.HISTORICO_REQUISICION.REQUISICION] FOREIGN KEY([COD_REQUISICION])
REFERENCES [REQUISICION].[REQUISICION] ([COD_REQUISICION])
GO
ALTER TABLE [REQUISICION].[HISTORICO] CHECK CONSTRAINT [FK_REQUISICION.HISTORICO_REQUISICION.REQUISICION]
GO
/****** Object:  ForeignKey [FK_REQUISICION.MENU_ROL_REQUISICION.OPCIONES_MENU]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [REQUISICION].[MENU_ROL]  WITH CHECK ADD  CONSTRAINT [FK_REQUISICION.MENU_ROL_REQUISICION.OPCIONES_MENU] FOREIGN KEY([COD_OPCIONES_MENU])
REFERENCES [REQUISICION].[OPCIONES_MENU] ([COD_OPCIONES_MENU])
GO
ALTER TABLE [REQUISICION].[MENU_ROL] CHECK CONSTRAINT [FK_REQUISICION.MENU_ROL_REQUISICION.OPCIONES_MENU]
GO
/****** Object:  ForeignKey [FK_REQUISICION.MENU_ROL_REQUISICION.ROL]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [REQUISICION].[MENU_ROL]  WITH CHECK ADD  CONSTRAINT [FK_REQUISICION.MENU_ROL_REQUISICION.ROL] FOREIGN KEY([COD_ROL])
REFERENCES [REQUISICION].[ROL] ([COD_ROL])
GO
ALTER TABLE [REQUISICION].[MENU_ROL] CHECK CONSTRAINT [FK_REQUISICION.MENU_ROL_REQUISICION.ROL]
GO
/****** Object:  ForeignKey [FK_REQUISICION.REQUISICION_REQUISICION.DIAS_LABORALES]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [REQUISICION].[REQUISICION]  WITH CHECK ADD  CONSTRAINT [FK_REQUISICION.REQUISICION_REQUISICION.DIAS_LABORALES] FOREIGN KEY([COD_DIA_LABORAL_DESDE])
REFERENCES [REQUISICION].[DIAS_LABORALES] ([COD_DIAS_LABORALES])
GO
ALTER TABLE [REQUISICION].[REQUISICION] CHECK CONSTRAINT [FK_REQUISICION.REQUISICION_REQUISICION.DIAS_LABORALES]
GO
/****** Object:  ForeignKey [FK_REQUISICION.REQUISICION_REQUISICION.DIAS_LABORALES1]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [REQUISICION].[REQUISICION]  WITH CHECK ADD  CONSTRAINT [FK_REQUISICION.REQUISICION_REQUISICION.DIAS_LABORALES1] FOREIGN KEY([COD_DIA_LABORAL_HASTA])
REFERENCES [REQUISICION].[DIAS_LABORALES] ([COD_DIAS_LABORALES])
GO
ALTER TABLE [REQUISICION].[REQUISICION] CHECK CONSTRAINT [FK_REQUISICION.REQUISICION_REQUISICION.DIAS_LABORALES1]
GO
/****** Object:  ForeignKey [FK_REQUISICION.REQUISICION_REQUISICION.TIPO]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [REQUISICION].[REQUISICION]  WITH CHECK ADD  CONSTRAINT [FK_REQUISICION.REQUISICION_REQUISICION.TIPO] FOREIGN KEY([COD_TIPO_REQUISICION])
REFERENCES [REQUISICION].[TIPO] ([COD_TIPO_REQUISICION])
GO
ALTER TABLE [REQUISICION].[REQUISICION] CHECK CONSTRAINT [FK_REQUISICION.REQUISICION_REQUISICION.TIPO]
GO
/****** Object:  ForeignKey [FK_REQUISICION.REQUISICION_REQUISICION.TIPO_DOCUMENTO]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [REQUISICION].[REQUISICION]  WITH CHECK ADD  CONSTRAINT [FK_REQUISICION.REQUISICION_REQUISICION.TIPO_DOCUMENTO] FOREIGN KEY([COD_TIPO_DOCUMENTO])
REFERENCES [REQUISICION].[TIPO_DOCUMENTO] ([COD_TIPO_DOCUMENTO])
GO
ALTER TABLE [REQUISICION].[REQUISICION] CHECK CONSTRAINT [FK_REQUISICION.REQUISICION_REQUISICION.TIPO_DOCUMENTO]
GO
/****** Object:  ForeignKey [FK_REQUISICION.REQUISICION_REQUISICION.TIPO_NECESIDAD]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [REQUISICION].[REQUISICION]  WITH CHECK ADD  CONSTRAINT [FK_REQUISICION.REQUISICION_REQUISICION.TIPO_NECESIDAD] FOREIGN KEY([COD_TIPO_NECESIDAD])
REFERENCES [REQUISICION].[TIPO_NECESIDAD] ([COD_TIPO_NECESIDAD])
GO
ALTER TABLE [REQUISICION].[REQUISICION] CHECK CONSTRAINT [FK_REQUISICION.REQUISICION_REQUISICION.TIPO_NECESIDAD]
GO
/****** Object:  ForeignKey [FK_RETIROS_ESTADOS]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [RETIROS].[RETIROS]  WITH CHECK ADD  CONSTRAINT [FK_RETIROS_ESTADOS] FOREIGN KEY([COD_ESTADO_RETIRO])
REFERENCES [RETIROS].[ESTADOS] ([COD_ESTADO_RETIRO])
GO
ALTER TABLE [RETIROS].[RETIROS] CHECK CONSTRAINT [FK_RETIROS_ESTADOS]
GO
/****** Object:  ForeignKey [FK_SOPORTES_RETIROS]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [RETIROS].[SOPORTES]  WITH CHECK ADD  CONSTRAINT [FK_SOPORTES_RETIROS] FOREIGN KEY([COD_RETIRO])
REFERENCES [RETIROS].[RETIROS] ([COD_RETIRO])
GO
ALTER TABLE [RETIROS].[SOPORTES] CHECK CONSTRAINT [FK_SOPORTES_RETIROS]
GO
/****** Object:  ForeignKey [FK_SOPORTES_TIPO_SOPORTES]    Script Date: 05/20/2019 10:20:34 ******/
ALTER TABLE [RETIROS].[SOPORTES]  WITH CHECK ADD  CONSTRAINT [FK_SOPORTES_TIPO_SOPORTES] FOREIGN KEY([COD_TIPO_SOPORTE])
REFERENCES [REFERENCIAS].[TIPO_SOPORTES] ([COD_TIPO_SOPORTE])
GO
ALTER TABLE [RETIROS].[SOPORTES] CHECK CONSTRAINT [FK_SOPORTES_TIPO_SOPORTES]
GO
