//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPOSITORIOS.REQUISICION_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORREOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CORREOS()
        {
            this.CORREOS_DESTINOS = new HashSet<CORREOS_DESTINOS>();
            this.PLANTILLAS_CORREOS = new HashSet<PLANTILLAS_CORREOS>();
        }
    
        public decimal COD_CORREO { get; set; }
        public decimal COD_TIPO_CORREO { get; set; }
        public string SERVIDOR_SMTP { get; set; }
        public string CUENTA_CORREO { get; set; }
        public string CUENTA { get; set; }
        public string SALTO { get; set; }
        public string IV { get; set; }
        public string CONTRASENA { get; set; }
        public bool ES_HTML { get; set; }
        public bool USA_SSL { get; set; }
        public decimal ESTADO { get; set; }
        public string COD_USUARIO_CREA { get; set; }
        public System.DateTime FECHA_CREA { get; set; }
        public string COD_USUARIO_MODIFICA { get; set; }
        public System.DateTime FECHA_MODIFICA { get; set; }
        public decimal PUERTO { get; set; }
        public string ASUNTO { get; set; }
    
        public virtual TIPOS_CORREOS TIPOS_CORREOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORREOS_DESTINOS> CORREOS_DESTINOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANTILLAS_CORREOS> PLANTILLAS_CORREOS { get; set; }
    }
}
