//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPOSITORIOS.REQUISICION_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTADOS()
        {
            this.RETIROS = new HashSet<RETIROS>();
        }
    
        public decimal COD_ESTADO_RETIRO { get; set; }
        public string NOMBRE { get; set; }
        public decimal ESTADO { get; set; }
        public string COD_USUARIO_CREA { get; set; }
        public System.DateTime FECHA_CREA { get; set; }
        public string COD_USUARIO_MODIFICA { get; set; }
        public System.DateTime FECHA_MODIFICA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETIROS> RETIROS { get; set; }
    }
}
