//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPOSITORIOS.REQUISICION_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODIFICACIONES
    {
        public decimal COD_AUDITORIA { get; set; }
        public decimal COD_TABLA { get; set; }
        public string TABLA { get; set; }
        public string COLUMNA { get; set; }
        public string DATO_ANTERIOR { get; set; }
        public string DATO_NUEVO { get; set; }
        public string COD_USUARIO_MODIFICO { get; set; }
        public System.DateTime FECHA_MODIFICACION { get; set; }
    }
}
