//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPOSITORIOS.REQUISICION_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUISICION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REQUISICION()
        {
            this.COMENTARIO = new HashSet<COMENTARIO>();
            this.HISTORICO = new HashSet<HISTORICO>();
        }
    
        public int COD_REQUISICION { get; set; }
        public Nullable<int> COD_TIPO_NECESIDAD { get; set; }
        public Nullable<int> COD_CARGO { get; set; }
        public string NOMBRE_CARGO { get; set; }
        public string ORDEN { get; set; }
        public string COD_CECO { get; set; }
        public string NOMBRE_CECO { get; set; }
        public Nullable<int> COD_TIPO_REQUISICION { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public Nullable<bool> ES_MODIFICACION { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<int> COD_ESTADO_REQUISICION { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<int> COD_GERENCIA { get; set; }
        public string NOMBRE_GERENCIA { get; set; }
        public Nullable<int> COD_TIPO_CONTRATO { get; set; }
        public string NOMBRE_TIPO_CONTRATO { get; set; }
        public Nullable<int> COD_TIPO_DOCUMENTO { get; set; }
        public string NUMERO_DOCUMENTO_EMPLEADO { get; set; }
        public string NOMBRE_EMPLEADO { get; set; }
        public string JEFE_INMEDIATO { get; set; }
        public Nullable<int> COD_SOCIEDAD { get; set; }
        public string NOMBRE_SOCIEDAD { get; set; }
        public Nullable<int> COD_EQUIPO_VENTAS { get; set; }
        public string NOMBRE_EQUIPO_VENTAS { get; set; }
        public Nullable<int> COD_CIUDAD_TRABAJO { get; set; }
        public string NOMBRE_CIUDAD_TRABAJO { get; set; }
        public Nullable<int> COD_DANE_CIUDAD_TRABAJO { get; set; }
        public Nullable<int> COD_UBICACION_FISICA { get; set; }
        public string NOMBRE_UBICACION_FISICA { get; set; }
        public Nullable<int> COD_NIVEL_RIESGO_ARL { get; set; }
        public string NIVEL_RIESGO_ARL { get; set; }
        public Nullable<int> COD_CATEGORIA_ED { get; set; }
        public string NOMBRE_CATEGORIA_ED { get; set; }
        public Nullable<bool> CARGO_CRITICO { get; set; }
        public Nullable<int> COD_JORNADA_LABORAL { get; set; }
        public string NOMBRE_JORNADA_LABORAL { get; set; }
        public string HORARIO_LABORAL_DESDE { get; set; }
        public string HORARIO_LABORAL_HASTA { get; set; }
        public Nullable<int> COD_DIA_LABORAL_DESDE { get; set; }
        public Nullable<int> COD_DIA_LABORAL_HASTA { get; set; }
        public string POSICION { get; set; }
        public string EMPRESA_TEMPORAL { get; set; }
        public Nullable<decimal> SALARIO_FIJO { get; set; }
        public Nullable<decimal> PORCENTAJE_SALARIO_FIJO { get; set; }
        public Nullable<decimal> SALARIO_VARIABLE { get; set; }
        public Nullable<decimal> PORCENTAJE_SALARIO_VARIABLE { get; set; }
        public Nullable<decimal> SOBREREMUNERACION { get; set; }
        public Nullable<decimal> PORCENTAJE_SOBREREMUNERACION { get; set; }
        public Nullable<decimal> EXTRA_FIJA { get; set; }
        public Nullable<decimal> RECARGO_NOCTURNO { get; set; }
        public Nullable<decimal> MEDIO_TRANSPORTE { get; set; }
        public Nullable<decimal> SALARIO_TOTAL { get; set; }
        public Nullable<decimal> BONO_ANUAL { get; set; }
        public Nullable<int> NUMERO_SALARIOS { get; set; }
        public Nullable<int> MESES_GARANTIZADOS { get; set; }
        public Nullable<int> COD_TIPO_SALARIO { get; set; }
        public string NOMBRE_TIPO_SALARIO { get; set; }
        public Nullable<decimal> FACTOR_PRESTACIONAL { get; set; }
        public Nullable<decimal> INGRESO_PROM_MENSUAL { get; set; }
        public Nullable<decimal> INGRESO_PROM_ANUAL { get; set; }
        public string MERCADO { get; set; }
        public Nullable<int> COD_CATEGORIA { get; set; }
        public string NOMBRE_CATEGORIA { get; set; }
        public Nullable<decimal> PUNTO_MEDIO_80 { get; set; }
        public Nullable<decimal> PUNTO_MEDIO_100 { get; set; }
        public Nullable<decimal> PUNTO_MEDIO_120 { get; set; }
        public Nullable<decimal> POSICIONAMIENTO { get; set; }
        public string EMAIL_USUARIO_CREACION { get; set; }
        public string LOGIN_EMPLEADO { get; set; }
        public Nullable<int> COD_HORARIO_LABORAL_DESDE { get; set; }
        public Nullable<int> COD_HORARIO_LABORAL_HASTA { get; set; }
        public Nullable<int> COD_MERCADO { get; set; }
        public string DIA_LABORAL_DESDE { get; set; }
        public string DIA_LABORAL_HASTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMENTARIO> COMENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORICO> HISTORICO { get; set; }
        public virtual TIPO TIPO { get; set; }
    }
}
