//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPOSITORIOS.REQUISICION_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETIROS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RETIROS()
        {
            this.SOPORTES = new HashSet<SOPORTES>();
        }
    
        public decimal COD_RETIRO { get; set; }
        public string NUMERO_DOCUMENTO { get; set; }
        public string NOMBRE { get; set; }
        public string USUARIO { get; set; }
        public decimal COD_CARGO { get; set; }
        public string NOMBRE_CARGO { get; set; }
        public decimal COD_CAUSA_RETIRO { get; set; }
        public string NOMBRE_CAUSA_RETIRO { get; set; }
        public System.DateTime FECHA_RETIRO { get; set; }
        public bool GENERA_VACANTE { get; set; }
        public string COMENTARIOS { get; set; }
        public bool APROBADO { get; set; }
        public decimal COD_ESTADO_RETIRO { get; set; }
        public decimal ESTADO { get; set; }
        public string COD_USUARIO_CREA { get; set; }
        public System.DateTime FECHA_CREA { get; set; }
        public string COD_USUARIO_MODIFICA { get; set; }
        public System.DateTime FECHA_MODIFICA { get; set; }
    
        public virtual ESTADOS ESTADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOPORTES> SOPORTES { get; set; }
    }
}
