//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REPOSITORIOS.REQUISICION_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL_REQUISICION
    {
        public int COD_ID_ROL_REQUISICION { get; set; }
        public string ID_ROL { get; set; }
        public Nullable<int> COD_TIPO_REQUISICION { get; set; }
        public Nullable<int> COD_ESTADO_REQUISICION { get; set; }
    }
}
